import { Roboto } from 'next/font/google';
import Head from 'next/head';

import Button from '@/components/ui/button';
import NextJsLogo from '@/assets/icons/nextjs.svg';

import { useCounterStore } from '@/hooks/use-counter-store';

const fontSans = Roboto({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function Home() {
  const counterStore = useCounterStore();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className={fontSans.variable}>
        <main>
          <NextJsLogo />
          <span>{counterStore.counter}</span>
          <Button label="Decrement" onClick={counterStore.onDecrement} />
          <Button label="Increment" onClick={counterStore.onIncrement} />
        </main>
      </div>
    </>
  );
}
