import { Roboto } from 'next/font/google';
import Head from 'next/head';

const fontSans = Roboto({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className={fontSans.variable}>
        <main>
          <h1>Hello World</h1>
        </main>
      </div>
    </>
  );
}
